import{a as B,i as n,S as $}from"./assets/vendor-DvfmeZXB.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const H="54239914-b8bb815315f9ce22f6479101b",b=async(r,i)=>{try{const{data:t}=await B.get("https://pixabay.com/api/",{params:{key:H,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:i,per_page:15}});return console.log("🚀 ~ getImagesByQuery ~ data:",t),t}catch(t){throw n.error({message:`${t}`,position:"topRight"}),t}},m=document.querySelector(".gallery"),c=document.querySelector(".loader"),s=document.querySelector(".loader-btn"),y=new $(".gallery a",{captionsData:"alt"});function w(r){if(!m)return;const i=r.map(({webformatURL:t,largeImageURL:a,tags:e,likes:o,views:d,comments:R,downloads:x})=>`<li>
  <a href='${a}'>
  <img src="${t}" alt="${e}" width = 360px height = 200px/>
  </a>
  <div class="text-img-engagement">
    <p>Likes <span>${o}</span></p>
    <p>View <span>${d}</span></p>
    <p>Comments <span>${R}</span></p>
    <p>Downloads <span>${x}</span></p>
  </div>
</li>`).join("");m.insertAdjacentHTML("beforeend",i),y&&y.refresh()}function P(){m.innerHTML=""}function v(){c&&(c.classList.remove("hidden","is-hidden"),c.style.display="")}function g(){c&&(c.classList.add("hidden","is-hidden"),c.style.display="none")}c&&g();function q(){s&&s.classList.remove("hidden")}function u(){s&&s.classList.add("hidden")}g();const E=document.querySelector(".form"),L=document.querySelector(".gallery li");let p="",l=1;const S=15;let f=0,h=!1;E.addEventListener("submit",N);s&&s.addEventListener("click",M);async function M(){if(!h&&p){l+=1,u(),v(),h=!0,s&&(s.disabled=!0);try{const r=await b(p,l);if(f=r.totalHits,!r.hits||r.hits.length===0){n.info({message:"No more images",position:"topRight"}),u();return}w(r.hits),requestAnimationFrame(()=>{const t=document.querySelectorAll(".gallery li"),a=t.length-r.hits.length,e=t[a]||t[0];if(e){const{height:o}=e.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}),l*S<f?q():(u(),n.info({message:"You've reached the end of search results.",position:"topRight"}))}catch(r){console.error(r),n.error({message:"Error fetching images",position:"topRight"})}finally{g(),h=!1,s&&(s.disabled=!1)}}}async function N(r){r.preventDefault();const i=r.target.elements["search-text"].value.trim();if(!i){n.info({message:"Введіть пошукове значення",position:"topRight"});return}p=i,l=1,f=0,u(),P(),v(),h=!0;try{const t=await b(p,l);if(f=t.totalHits,t.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}if(w(t.hits),L){const{height:e}=L.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}l*S<f?q():(u(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(t){console.error(t),n.error({message:"Error fetching images",position:"topRight"})}finally{g(),h=!1}}
//# sourceMappingURL=index.js.map
