import{a as B,i as a,S as $}from"./assets/vendor-DvfmeZXB.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const i of e)if(i.type==="childList")for(const l of i.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function t(e){const i={};return e.integrity&&(i.integrity=e.integrity),e.referrerPolicy&&(i.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?i.credentials="include":e.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function n(e){if(e.ep)return;e.ep=!0;const i=t(e);fetch(e.href,i)}})();const H="54239914-b8bb815315f9ce22f6479101b",L=async(r,o)=>{try{const{data:t}=await B.get("https://pixabay.com/api/",{params:{key:H,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}});return console.log("🚀 ~ getImagesByQuery ~ data:",t),t}catch(t){throw a.error({message:`${t}`,position:"topRight"}),t}},g=document.querySelector(".gallery"),h=document.querySelector(".loader"),s=document.querySelector(".loader-btn"),m=new $(".gallery a",{captionsData:"alt"});function b(r){if(!g)return;const o=r.map(({webformatURL:t,largeImageURL:n,tags:e,likes:i,views:l,comments:R,downloads:x})=>`<li>
  <a href='${n}'>
  <img src="${t}" alt="${e}" width = 360px height = 200px/>
  </a>
  <div class="text-img-engagement">
    <p>Likes <span>${i}</span></p>
    <p>View <span>${l}</span></p>
    <p>Comments <span>${R}</span></p>
    <p>Downloads <span>${x}</span></p>
  </div>
</li>`).join("");g.insertAdjacentHTML("beforeend",o),m&&m.refresh()}function P(){g.innerHTML=""}function w(){h&&h.classList.remove("hidden")}function v(){h&&h.classList.add("hidden")}function S(){s&&s.classList.remove("hidden")}function d(){s&&s.classList.add("hidden")}const E=document.querySelector(".form"),y=document.querySelector(".gallery li");let p="",c=1;const q=15;let u=0,f=!1;E.addEventListener("submit",O);s&&s.addEventListener("click",M);async function M(){if(!f&&p){c+=1,d(),w(),f=!0,s&&(s.disabled=!0);try{const r=await L(p,c);if(u=r.totalHits,!r.hits||r.hits.length===0){a.info({message:"No more images",position:"topRight"}),d();return}b(r.hits);const o=document.querySelector(".gallery li");if(o){const{height:n}=o.getBoundingClientRect();window.scrollBy({top:n*2,behavior:"smooth"})}c*q<u?S():(d(),a.info({message:"You've reached the end of search results.",position:"topRight"}))}catch(r){console.error(r),a.error({message:"Error fetching images",position:"topRight"})}finally{v(),f=!1,s&&(s.disabled=!1)}}}async function O(r){r.preventDefault();const o=r.target.elements["search-text"].value.trim();if(!o){alert("Введіть пошукове значення");return}p=o,c=1,u=0,d(),P(),w(),f=!0;try{const t=await L(p,c);if(u=t.totalHits,t.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}if(b(t.hits),y){const{height:e}=y.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}c*q<u?S():(d(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(t){console.error(t),a.error({message:"Error fetching images",position:"topRight"})}finally{v(),f=!1}}
//# sourceMappingURL=index.js.map
